package ca.mcgill.ecse.flexibook.application;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.Owner;
import ca.mcgill.ecse.flexibook.model.User;
import ca.mcgill.ecse.flexibook.model.*;

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.Owner;
import ca.mcgill.ecse.flexibook.model.User;
import ca.mcgill.ecse.flexibook.model.*;
import ca.mcgill.ecse.flexibook.persistence.FlexiBookPersistence;
import ca.mcgill.ecse.flexibook.view.FbsPage;

public class FlexiBookApplication {

	
	private static FlexiBook fbs;
	private static User u;
	private static SystemTime dateAndTime;

	

    public static void main(String[] args) {
    	java.awt.EventQueue.invokeLater(new Runnable() {
    		public void run() {
    			new FbsPage().setVisible(true);
    		}
    	});
    }


    public FlexiBookApplication() {
    	dateAndTime = new SystemTime();
    }

    public static FlexiBook getFlexiBook() {
    	if (fbs == null) {
			// now we load the application
            fbs = FlexiBookPersistence.load(); // This line is updated
		}
 		return fbs;
    }
    
    public static User getCurrentUser() {
 		return u;
    }
    
    public static boolean setCurrentUser(User user) {
    	boolean wasSet = false;
    	u = user;
    	wasSet = true;
 		return wasSet;
    }
    
}
